version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG            
        formatter: simple
        filename: log/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

    standard_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO            
        formatter: simple
        filename: log/standard.log
        maxBytes: 10485760 # 10MB
        backupCount: 1
        encoding: utf8

    warning_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING            
        formatter: simple
        filename: log/warning.log
        maxBytes: 10485760 # 10MB
        backupCount: 1
        encoding: utf8

loggers:
    __main__:
        level: DEBUG
        handlers: [console, debug_file_handler, standard_file_handler, warning_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, standard_file_handler, warning_file_handler]


# https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/